WIP: Further updates to Windows installation instructions
JMRI/website pull request #468
Opened 2022-04-13 19:52 UTC by jerryg2003

TBD: Fix missing vertical and horizontal scroll bars (need info from @silverailscolo)

2022-04-13 20:12 UTC, bobjacobsen approved these changes

2022-04-13 20:13 UTC, bobjacobsen commented
Not a windows user, but it looks OK to me.

2022-04-13 20:47 UTC, dsand47 requested changes

2022-04-13 20:47 UTC, dsand47 commented on install/WindowsNew.shtml
> +        <p style="text-align:center;"><img src="images/Windows10-4995-Setup.jpg" alt="installer welcome page"></p></li>
This image is missing.

2022-04-13 20:47 UTC, dsand47 commented on install/WindowsNew.shtml
> +        <p style="text-align:center;"><img src="images/426-NoJavaFound.jpg" alt="No Java found - suggest Java 8"></p>
Image missing.

2022-04-13 20:47 UTC, dsand47 commented on install/WindowsNew.shtml
> +        <p style="text-align:center;"><img src="images/4995-NoJavaFound.jpg" alt="No Java found - suggest Java 11"></p>
Image missing.

2022-04-13 20:56 UTC, jerryg2003 commented on install/WindowsNew.shtml
> +        <p style="text-align:center;"><img src="images/Windows10-4995-Setup.jpg" alt="installer welcome page"></p></li>
Sorry about that...

2022-04-13 21:26 UTC, dsand47 approved these changes
Minor oversight:  install/images/Windows10-4995-Complete.jpg not referenced by the html.

2022-04-13 22:51 UTC, jerryg2003 commented
> Minor oversight: install/images/Windows10-4995-Complete.jpg not referenced by the html.

Yeah, saw that.  Thanks. Will get it in the next Commit (when I figure out fix to be scrolling).

2022-04-19 17:24 UTC, silverailscolo approved these changes
Clean tags, thanks

2022-04-23 15:26 UTC, jerryg2003 commented
@bobjacobsen @silverailscolo Can you merge and we can see what happens with the scrolling?  Thanks.

2022-04-23 15:27 UTC, merged

2022-04-24 20:57 UTC, silverailscolo commented
The scroll bar remains hidden. I will look for a fix embedding the long line of code "WARN - Could not open/create prefs...".